### PR TITLE
Feature: Fixed Left Course Navigation

### PR DESCRIPTION
**Pull request by Mando75**
This adds a feature to your Canvas Search Extension to optionally fix the position of the Course Navigation Menu when scrolling. The top/left styling is still a couple pixels off of the official styling, but it does not seem to be noticeable. 

Please note that I haven't tested this exhaustively to see if it has any malicious side effects, but it seems to be working properly.

### CODE REVIEW

**Comment by Mando75** [comment]
I just realized that I wrote the styling specifically for the compact global navigation... I will take a look to see if I can make it more dynamic

**Comment by Mando75** [comment]
It should now handle the size of the global navigation menu. I am not familiar with the onclick listeners in Canvas, and I didn't really have time to research them. An upgrade would be to have an even listener on the global menu that would toggle the position of the course navigation. That may not be necessary though, considering they will be changing the global css soon.

**Comment by danverde** [comment]
The sticky course nav feature will be pushed to the overall BYUI CSS file on its next update & will apply across all of byui.instructure.com

**Comment by Mando75** [comment]
Sounds good. This was just a temporary fix until that took place.

**Pull request closed without merging**
